#!/usr/bin/env pizx
/**
 * ─── heal-build.mjs — Broken Build Auto-Healer ────────────────────────────
 *
 * When tests fail, this script uses a Ralph Loop to diagnose, plan, fix,
 * verify, and review — iterating until tests pass or max iterations.
 *
 * How it works:
 *   Analyze → "What failed and why?"
 *   Plan    → "What's the minimal fix?"
 *   Execute → Apply fix (edit file)
 *   Verify  → Re-run the failing test
 *   Review  → Did it pass? What did we learn?
 *
 * The loop repeats up to 3 times. If tests still fail, produces an
 * analysis report instead of a broken patch.
 *
 * Output: cumulative .patch in self-improve-examples/patches/heal-build/
 *
 * Run:
 *   pizx self-improve-examples/heal-build.mjs
 *   TEST_FILTER=ralph pizx self-improve-examples/heal-build.mjs   # only ralph tests
 */

import { chalk } from 'zx'
import { writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'

const PLANNER_MODEL = 'deepseek/deepseek-v4-pro'
const WORKER_MODEL = 'deepseek/deepseek-v4-flash'
const PATCHES_DIR = join(import.meta.dirname, 'patches', 'heal-build')
const TEST_FILTER = process.env.TEST_FILTER || ''
const MAX_ITERATIONS = 3

// ════════════════════════════════════════════════════════════════════════

console.log(chalk.bold.green('\n 🩺 Heal Build — Broken Test Auto-Healer\n'))
console.log(chalk.dim(` Planner: ${PLANNER_MODEL}  |  Worker: ${WORKER_MODEL}\n`))
console.log(chalk.dim(` Max iterations: ${MAX_ITERATIONS}${TEST_FILTER ? `  |  Filter: ${TEST_FILTER}` : ''}\n`))

await mkdir(PATCHES_DIR, { recursive: true })

// ─── Run failing tests ───────────────────────────────────────────────────

console.log(chalk.yellow(' Running tests to find failures...\n'))

let testOutput = ''
try {
  const filterArgs = TEST_FILTER ? ['-t', TEST_FILTER] : []
  const cmd = ['npx', 'vitest', '--run', '--reporter=verbose', ...filterArgs, '2>&1', '||', 'true']
  testOutput = (await $`${cmd}`).stdout.trim()
} catch {
  testOutput = (await $`npx vitest --run 2>&1 || true`).stdout.trim()
}

// Check if tests are already passing
const failedCount = (testOutput.match(/(\d+)\s+failed/)?.[1]) || '0'
const passedCount = (testOutput.match(/(\d+)\s+passed/)?.[1]) || '0'

console.log(chalk.dim(`   Tests: ${passedCount} passed, ${failedCount} failed\n`))

if (parseInt(failedCount) === 0) {
  console.log(chalk.green(' ✓ All tests passing! Nothing to heal.\n'))
  process.exit(0)
}

// ─── Ralph Loop: heal failing tests ──────────────────────────────────────

console.log(chalk.yellow(` Starting Ralph Loop — healing ${failedCount} failing test(s)...\n`))

const ralphResult = await ralph({
  plannerModel: PLANNER_MODEL,
  workerModel: WORKER_MODEL,
  maxIterations: MAX_ITERATIONS,
  useTools: true,
})`
The pizx project has failing tests. Your job is to fix the SOURCE CODE (not the tests) so that all tests pass. Tests define expected behavior — fix the implementation, not the expectations.

Failing test output:
${testOutput.slice(0, 10000)}

Instructions for each iteration:
1. ANALYZE: Read the failing test to understand expected behavior. Read the source file it tests.
2. PLAN: What's the minimal fix that would make this test pass? Think small — one function, one line if possible.
3. EXECUTE: Edit the source file to implement the fix.
4. VERIFY: Run ONLY the failing test(s) with: npx vitest --run -t "${TEST_FILTER || 'the failing test name'}"
5. REVIEW: Did it pass? If not, what else is needed?

Important:
- Fix the SOURCE CODE, not the test files
- Make minimal changes — one fix at a time
- After each fix, run the specific test to verify
- If tests pass after a fix, explain what you changed and why
- If you can't fix after ${MAX_ITERATIONS} iterations, explain what's blocking you

At the end, provide:
1. What was fixed (file, line, what changed)
2. What's still failing (if anything)
3. An assessment of whether the remaining failures are in the implementation or the tests

DO NOT wrap in markdown fences.
`

// ─── Generate .patch with Ralph Loop audit trail ─────────────────────────

const ralphText = ralphResult.text || ''
const iterations = ralphResult.iterationCount || 0

console.log(chalk.yellow(' Generating cumulative .patch with audit trail...\n'))

const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
const patchName = `${timestamp}-heal-${MAX_ITERATIONS}-iterations.patch`

// Extract fixes from Ralph text
const fixSections = ralphText.split(/EXECUTE|FIX|CHANGE|EDIT/i).filter(s =>
  s.includes('src/') || s.includes('edit') || s.includes('write') || s.includes('diff')
)

const auditTrail = ralphText.slice(0, 3000)

const patchContent = [
  `# Generated by: heal-build.mjs`,
  `# Date: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`,
  `# Iterations: ${iterations}/${MAX_ITERATIONS}`,
  `# Test filter: ${TEST_FILTER || 'all'}`,
  `# Initial state: ${passedCount} passed, ${failedCount} failed`,
  ``,
  `# ─── Ralph Loop Audit Trail ───`,
  `# ${auditTrail.replace(/\n/g, '\n# ')}`,
  ``,
  `# ─── Fixes ───`,
  fixSections.join('\n\n') || '# No fixes could be generated — see audit trail above',
  ``,
].join('\n')

await writeFile(join(PATCHES_DIR, patchName), patchContent, 'utf-8')

// ─── Report ──────────────────────────────────────────────────────────────

console.log(chalk.bold.green(`\n ✓ Heal build complete — ${iterations} iteration(s)\n`))

// Re-run tests to get final count
let finalOutput = ''
try {
  finalOutput = (await $`npx vitest --run ${TEST_FILTER ? `-t ${TEST_FILTER}` : ''} 2>&1 || true`).stdout.trim()
} catch {
  finalOutput = ''
}

const finalFailed = (finalOutput.match(/(\d+)\s+failed/)?.[1]) || failedCount
const finalPassed = (finalOutput.match(/(\d+)\s+passed/)?.[1]) || passedCount

console.log(chalk.dim(`   Before: ${passedCount} passed, ${failedCount} failed`))
console.log(chalk.dim(`   After:  ${finalPassed} passed, ${finalFailed} failed\n`))

if (parseInt(finalFailed) === 0) {
  console.log(chalk.green(' 🎉 All tests now passing!\n'))
} else {
  console.log(chalk.yellow(` ⚠ ${finalFailed} test(s) still failing after ${iterations} iterations`))
  console.log(chalk.dim('   Review the audit trail in the .patch file for analysis\n'))
}

console.log(chalk.white(`   Patch: ${PATCHES_DIR}/${patchName}`))
console.log(chalk.dim('   Review and apply with: git apply') + chalk.white(` ${PATCHES_DIR}/${patchName}\n`))
console.log(chalk.dim(' ─── Heal the code, not the test expectations ───\n'))
